<a href="https://colab.research.google.com/github/muhammetaslan/python/blob/master/python_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

cal_A = np.array([[56.0,0.0,4.4,68.0],
                [1.2,104.0,52.0,8.0],
                [1.8,135.0,99.0,0.9]])

print(cal_A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [18]:
# axis= 0 means sum vertically
# axis= 1 means sum horizantaly
cal = cal_A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [19]:
# cal.reshape(1,4) burada etkisi yok zaten cal [1,4] lük matrix suan
percentage = 100*cal_A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [25]:
array_1 = np.random.rand(5,5)
print(array_1)

[[0.62535087 0.942588   0.87953315 0.45036506 0.7452687 ]
 [0.8511633  0.49421928 0.83011702 0.96696692 0.23529213]
 [0.82260354 0.69310598 0.89235477 0.16510652 0.95613376]
 [0.955396   0.10187427 0.89774094 0.46045346 0.94570448]
 [0.81465689 0.00424998 0.55847992 0.4563948  0.72691985]]


In [27]:
# python broadcasting sample
array_1 += 2
print(array_1)

[[2.62535087 2.942588   2.87953315 2.45036506 2.7452687 ]
 [2.8511633  2.49421928 2.83011702 2.96696692 2.23529213]
 [2.82260354 2.69310598 2.89235477 2.16510652 2.95613376]
 [2.955396   2.10187427 2.89774094 2.46045346 2.94570448]
 [2.81465689 2.00424998 2.55847992 2.4563948  2.72691985]]
